// flow-typed signature: ee51b512fb7939980610e35462569242
// flow-typed version: <<STUB>>/@commitlint/cli_v^16.2.1/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@commitlint/cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@commitlint/cli' {
  declare module.exports: any;
}
