// flow-typed signature: 57351b40a8359ae26879210465f6b9da
// flow-typed version: <<STUB>>/@commitlint/config-conventional_v^16.2.1/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@commitlint/config-conventional'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@commitlint/config-conventional' {
  declare module.exports: any;
}
