// flow-typed signature: 3f15389d4b64e16afbe5b322b0784ed7
// flow-typed version: <<STUB>>/husky_v^7.0.4/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'husky'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'husky' {
  declare module.exports: any;
}
