// flow-typed signature: 02e00596c36db1fd06eadf41e71f9865
// flow-typed version: <<STUB>>/lint-staged_v^12.4.0/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lint-staged'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lint-staged' {
  declare module.exports: any;
}
