// flow-typed signature: 84ff87a30bde022c60e59edfba5190b1
// flow-typed version: <<STUB>>/standard-version_v^9.3.2/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'standard-version'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'standard-version' {
  declare module.exports: any;
}
