// flow-typed signature: f9d31b01ab7e20cccd0c7e6bc7415dc7
// flow-typed version: <<STUB>>/@krakenjs/grumbler-scripts_v^8.0.4/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@krakenjs/grumbler-scripts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@krakenjs/grumbler-scripts' {
  declare module.exports: any;
}
